# Skribki Wiki CI configuration.
# https://travis-ci.org/VevoxDigital/Skribki

language: node_js
node_js:
- 'stable' # latest stable
- '10.0'   # minimum

# Install necessary packages before runtime
install:
- yarn global add ts-node mocha @types/mocha chai @types/chai nyc
- yarn

# Build only master/dev. Other branches are docs, examples, or legacy.
branches:
  only:
  - master

addons:
  code_climate:
    repo_token: 7fa84e1393a582d1023c7cf39e64a35c14ab52c6fd78b81edf44b1d213cf9f41

after_success:
- yarn global add codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
